# example of contract tests using variables validation
variable "region" {
  description = "AWS region"
  type        = string

  # list of regions in AWS was generated by command:
  # for r in $(aws ec2 describe-regions --query 'Regions[*].RegionName' --output text); do echo $r; done
  validation {
    condition     = contains(["ap-northeast-1", "ap-northeast-2", "ap-northeast-3", "ap-south-1", "ap-southeast-1", "ap-southeast-2", "ca-central-1", "eu-central-1", "eu-north-1", "eu-west-1", "eu-west-2", "eu-west-3", "sa-east-1", "us-east-1", "us-east-2", "us-west-1", "us-west-2"], var.region)
    error_message = "The AWS region name is invalid."
  }
}

variable "prefix" {
  description = "Prefix added to name of all resources"
  type        = string

  # limit of 16 characters for prefix is only used as an example - in AWS tag name can have maximum 128 characters
  validation {
    condition     = length(var.prefix) < 16
    error_message = "The prefix value must be shorter that 16 characters."
  }
}

variable "runtime" {
  description = "Runtime envinronment used to execute code"
  type        = string
  default     = "python3.9"
}
