[tool.poetry]
name = "ansible-local"
version = "0.1.0"
description = ""
authors = ["Sebastian Czech <sebaczech@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ansible = "^9.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
